#+TITLE: Inflation
#+AUTHOR: Rémi Louf
#+PROPERTY: header-args :db us-prices.db


#+begin_src elisp
(pyvenv-workon 'inflation)
#+end_src

The idea is that while the CPI reflects a reality, this reality is not perceived the same everywhere (regional differences) and by everyone (basket differences). It is also not very actionable since variations are likely to be differentiated between items.

* How to compute the CPI from individual price indices

There is a formula with weights, but there is no way I am going to have enought time to compute all the weights from data; even if I had infinite time I would have a hard time reproduce the BLS's exact CPI value. But this is not what is important here. So we can randomize or play with the weights.

1. Find set of weights s.t. changes are minimized

* Decompose the CPI

First let's plot the time series for Broccoli:

#+begin_src sqlite :colname yes
SELECT area_code, year, month, index_value FROM series
WHERE item_code = 712412
ORDER BY area_code, year, month
LIMIT 10
#+end_src

#+RESULTS:
| 0 | 1995 |  7 | 0.907 |
| 0 | 1995 |  8 | 0.889 |
| 0 | 1995 |  9 | 0.937 |
| 0 | 1995 | 10 | 0.867 |
| 0 | 1995 | 11 |   0.8 |
| 0 | 1995 | 12 | 0.759 |
| 0 | 1996 |  1 | 1.037 |
| 0 | 1996 |  2 | 0.926 |
| 0 | 1996 |  3 | 0.999 |
| 0 | 1996 |  4 | 0.941 |

#+begin_src python
import sqlite3

query = """SELECT area_code, year, month, index_value FROM series
           WHERE item_code = 712412 -- broccoli
           ORDER BY area_code, year, month"""
#+end_src

/Wild idea:/ inflation is the result of normal market competition, price slippage is to be expect in a competitive environment.

* TODO How is the CPI built from the individual price indices? :noexport:
* TODO Plot all prices and average CPI (item difference) :noexport:
* TODO Plot CPIs for every region on the same plot as well (geographical difference) :noexport:
* TODO At any given point in time, distribution of increase in CPI/region :noexport:
* TODO At any given point in time, distribution of increase in CPI/item :noexport:
* TODO Ranking in inflation increase / for each item, over time. :noexport:
* TODO Alternative CPI with randomly assigned weights in the basket (use Dirichlet distribution) :noexport:
* TODO Plot the % of indices that have rose by more than X% in the last period :noexport:

* References :noexport:

- [[https://en.wikipedia.org/wiki/Quantity_theory_of_money][Wikipedia entry]] on the Quantity Theory of Money, a theory used to "explain" inflation;
- [[http://jwmason.org/slackwire/inflation-for-whom/]["Inflation for whom?"]] a blog post by JW Mason
- [[http://jwmason.org/slackwire/alternative-visions-of-inflation/]["Alternative visions of inflation"]] a blog post by JW Mason as well
